### ISSUE TITLE
Errors and shut down after start

### ISSUE THREAD

**Issue by passuff** [MeisterTR/ioBroker.yeelight#150]
When I try to start the instance I receive the following errors:

```
2022-01-27 08:12:28.787 - info: host.iobrokerV2 instance system.adapter.yeelight-2.0 started with pid 991
--
2022-01-27 08:12:29.883 - debug: yeelight-2.0 (991) Redis Objects: Use Redis connection: 127.0.0.1:9001
2022-01-27 08:12:30.126 - debug: yeelight-2.0 (991) Objects client ready ... initialize now
2022-01-27 08:12:30.129 - debug: yeelight-2.0 (991) Objects create System PubSub Client
2022-01-27 08:12:30.139 - debug: yeelight-2.0 (991) Objects create User PubSub Client
2022-01-27 08:12:30.141 - debug: yeelight-2.0 (991) Objects client initialize lua scripts
2022-01-27 08:12:30.209 - debug: yeelight-2.0 (991) Objects connected to redis: 127.0.0.1:9001
2022-01-27 08:12:30.234 - debug: yeelight-2.0 (991) objectDB connected
2022-01-27 08:12:30.236 - debug: yeelight-2.0 (991) Redis States: Use Redis connection: 127.0.0.1:9000
2022-01-27 08:12:30.304 - debug: yeelight-2.0 (991) States create System PubSub Client
2022-01-27 08:12:30.306 - debug: yeelight-2.0 (991) States create User PubSub Client
2022-01-27 08:12:30.323 - debug: yeelight-2.0 (991) States connected to redis: 127.0.0.1:9000
2022-01-27 08:12:30.324 - debug: yeelight-2.0 (991) statesDB connected
2022-01-27 08:12:30.626 - info: yeelight-2.0 (991) starting. Version 1.1.2 in /opt/iobroker/node_modules/iobroker.yeelight-2, node: v14.18.3, js-controller: 3.3.22
2022-01-27 08:12:30.659 - debug: yeelight-2.0 (991) DEVICES IN CONFIG: [{"name":"NachttischlampeNelia","ip":"192.168.1.118","port":"55443","smart_name":"","type":"bslamp1","id":"0x000000001017f710"},{"name":"NachttischlampeJanna","ip":"192.168.1.241","port":"55443","smart_name":"","type":"bslamp1","id":"0x000000000000001","supports":["get_prop","set_default","set_power","toggle","set_bright","start_cf","stop_cf","set_scene","cron_add","cron_get","cron_del","set_ct_abx","set_rgb","set_hsv","set_adjust","adjust_bright","adjust_ct","adjust_color","set_music","set_name"]}]
2022-01-27 08:12:30.746 - debug: yeelight-2.0 (991) DEVICES IN OBJECTS: {"yeelight-2.0.NachttischlampeNelia":{"type":"device","common":{"name":"bslamp1","icon":"/icons/bslamp1.png"},"native":{"sid":"NachttischlampeNelia","type":"bslamp1"},"from":"system.adapter.yeelight-2.0","user":"system.user.admin","ts":1643224420931,"_id":"yeelight-2.0.NachttischlampeNelia","acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"},"enums":{}},"yeelight-2.0.NachttischlampeJanna":{"type":"device","common":{"name":"bslamp1","icon":"/icons/bslamp1.png"},"native":{"sid":"NachttischlampeJanna","type":"bslamp1"},"from":"system.adapter.yeelight-2.0","user":"system.user.admin","ts":1643224420933,"_id":"yeelight-2.0.NachttischlampeJanna","acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"},"enums":{}}}
2022-01-27 08:12:30.747 - debug: yeelight-2.0 (991) DEVICES IN OBJECTS FOUND: 2
2022-01-27 08:12:30.747 - debug: yeelight-2.0 (991) OBJ_ELEMENT: yeelight-2.0.NachttischlampeNelia
2022-01-27 08:12:30.749 - debug: yeelight-2.0 (991) OBJ_ELEMENT: yeelight-2.0.NachttischlampeJanna
2022-01-27 08:12:30.754 - error: yeelight-2.0 (991) uncaught exception: Cannot read property 'val' of null
2022-01-27 08:12:30.755 - error: yeelight-2.0 (991) TypeError: Cannot read property 'val' of null
at Immediate. (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:291:62)
at processImmediate (internal/timers.js:466:21)
2022-01-27 08:12:30.756 - error: yeelight-2.0 (991) Cannot read property 'val' of null
2022-01-27 08:12:30.759 - info: yeelight-2.0 (991) cleaned everything up...
2022-01-27 08:12:30.759 - info: yeelight-2.0 (991) terminating
```

Here is my config:

```
iopassuff@iobrokerV2:~$ iobroker info
Platform       : linux
os             : linux
Architecture   : x64
CPUs           : 2
Speed          : 1699 MHz
Model          : Common KVM processor
RAM            : 3.8 GB
System uptime  : 00:09:38
Node.js        : v14.18.3
Disk size      : 30.4 GiB
Disk free      : 27.4 GiB
adapters count : 472
NPM            : v6.14.15


```

**Comment by Apollon77** [comment]
Please try GitHub version
